- src/convertFromHTML.js
- test/spec/convertFromHTML.js
I forgot to make the same undefined check in both places where we handle the new block metadata in #9 to default to an empty object 😶
> convertFromHTML: fix nested default blocks

- src/encodeBlock.js
- test/spec/blockEntities.js
fix issue with HTML escaping multiple characters when updating other mutations (entities, styles) using an index that hasn't been updated to account for previous HTML escaping changes.
e.g. if two quotes are each replaced with `&quot;` the second must update further mutations based on its new position after the first quote was already replaced with a longer string.
> fix HTML escaping multiple characters along with other entities/styles

- src/convertFromHTML.js
- test/spec/convertFromHTML.js
This can cause issues with other links within atomic blocks since it doesn't have the same checks to prevent issues with creating text via [this temporary hack](https://github.com/HubSpot/draft-convert/blob/master/src/convertFromHTML.js#L371-L378). This could be just made to watch out for that but it feels like something that shouldn't be in the project, since links aren't natively rendered by Draft.
> Remove built-in link conversion from convertFromHTML

- webpack.config.base.js
1.3.0 imports `react` and `react-dom/server`, but I missed adding them to externals to keep them out of the webpack output 😬
> Add React & ReactDOM to externals

- src/convertFromHTML.js
Defaulting to `unstyled` was a bad idea, since any inline element would then count as an unstyled block. Defining `div` and `p` should complete the set of supported block tags out of the box, with any custom functionality able to iterate on top of it with `htmlToBlock` middleware
> Fix block conversion from HTML to only include defined elements

- README.md
makes it easier to get to npm (since there isn't a link in readme currently) 🎉
> add npm/license badges to readme

- src/convertToHTML.js
- src/util/getBlockTags.js
- test/spec/getBlockTags.js
A common block type conversion for an atomic block will include the wrapping tag as well as content within, e.g.: 
```javascript
return (
<figure><img src={src} /></figure>
);
```
This PR allows children of the root React element in the returned value to be rendered along with the wrapping element if it exists. I also added some additional base tests for `getBlockTags`.
Empty React elements returned will continue to act as usual
> Render block children

- package.json
Hi, please check this.
I think that version of `immutable` should be the same as `draft-js` .
ref: https://github.com/facebook/draft-js/blob/0.10-stable/package.json#L34
> Fix version of immutable.js

- src/blockEntities.js
- src/encodeBlock.js
- src/util/updateMutation.js
- test/spec/convertToHTML.js
This PR address an issue where if an inline style is applied within the range of an entity, the conversion to HTML creates invalid HTML markup.
For example, if a link is partially italicized and partially bolded:
[**Hello** *World*](http://google.com)
Currently, the html output is something like:
```
<p><strong><a hr</strong>e<em>f="ht</em>tp://google.com">Hello World</a></p>
```
The expected output is:
```
<p><a href="http://google.com"><strong>Hello</strong> <em>World</em></a></p>
```
This PR fixes the issue by accepting an entity config that returns `{start, end}`. Then it uses the length of `start` as the prefix length. If an inline style mutation starts after the original offset, but ends before the entity range ends, we increase the offset by just the prefix length. If the inline …
> Fix overlapping styles and entities in convertToHTML

- src/blockEntities.js
- src/util/getElementPrefix.js
- test/spec/convertToHTML.js
follow-up to https://github.com/HubSpot/draft-convert/pull/43 - calculate entity prefixes for  `ReactElement`s in addition to `{ start, end }` HTML objects. Abstracted the logic out into a separate module as well and added a slightly modified test to describe this case.
> Support ReactElement entity conversion for nested styles

- src/convertFromHTML.js
Above `nodeName` correctly becomes `child.nodeName.toLowerCase()`, so the matching `child` should be passed instead of its parent.
> Fix erroneous second argument to `checkBlockType`

- src/convertFromHTML.js
- test/spec/convertFromHTML.js
Fixes additional comments in #22 by @khrykin
Completely omits any whitespace outside of any identified block. Whitespace within blocks are useful and probably necessary to keep, especially in the case of atomic blocks that use entity data on a single space character.
> omit whitespace in HTML input

- src/blockEntities.js
- src/encodeBlock.js
- src/util/getElementTagLength.js
- src/util/updateMutation.js
- test/spec/convertToHTML.js
My stab at fixing #46.
Address styles that intersect with entities that have a prefix/suffix conversion strategy by splitting the style's mutation into two ranges - one inside the entity's tag, one outside. I also added some better naming to conditions in `updateMutation` to make it more readable.
Thanks to @liyantang for pushing the ball forward here and for the tests which I included in this PR. One of the ended up outputting a slightly different nesting order but I believe it should still be equivalent.
> Handle intersecting mutations

- src/util/splitReactElement.js
- test/spec/convertToHTML.js
Fixes https://github.com/HubSpot/draft-convert/issues/30
Adds an exception list from [W3C](http://w3c.github.io/html/syntax.html#writing-html-documents-elements) and doesn't try to split those elements into `start` and `end` tags, instead just returning a single string.
> Handle void HTML elements

- src/blockEntities.js
- src/util/updateMutation.js
- test/spec/convertToHTML.js
Fixes example from @liyantang in #66
- Stops updating mutations with themselves in `blockEntities`, since that now would create a different result
- Restrict conditions for overlapping with a prefix/suffix to be accurate
> Fix containing mutation

- README.md
- src/convertFromHTML.js
- test/spec/convertFromHTML.js
Addresses #58
Returning `false` in `htmlToBlock` will cause the node to get ignored entirely when building content state (including any contents).
> Omit blocks in convertFromHTML

- src/util/getElementTagLength.js
- test/spec/.eslintrc
- test/spec/blockEntities.js
- test/spec/convertToHTML.js
- test/spec/updateMutation.js
Fixes #76 
Adding @ryanscottaudio's changes here so that they can get out ASAP. The only real change was using `React.Children.only` instead of `React.Children.toArray`, which I think will be more useful to someone who was confused by the behavior if they were passing multiple sibling children.
I added some tests that cover a couple levels of the problem that were useful to diagnose the problem along the way, including a set of tests for each case of `updateMutation`.
Thanks @ryanscottaudio for identifying the problem and scoping out the solution!
> Fix overlapping entity conversion within React components

- README.md
- src/convertFromHTML.js
- test/spec/convertFromHTML.js
Fixes #38 
First real pass at getting this working without using `Entity.create`. Essentially an empty`ContentState` is created before conversion begins, and a function is passed down to be called on the result of `textToEntity` or `htmlToEntity` to create an entity on that contentState. Those `*ToEntity` methods now return an object of shape `{type, mutability, data}`.
An alternative that I thought of while writing this was to instead pass that function as an additional argument to the`*ToEntity` functions themselves so that they can return with the string result of an `Entity.create`-like function like before. This would also make it easier for users to track down issues if there were an exception when creating the entity since it would be called from their own code at some point.
> use new Entity API

- src/util/getElementHTML.js
- src/util/getElementTagLength.js
- test/spec/blockEntities-test.js
fixes #101 
I think this was an issue I ran into when trying to integrate flow, but it never made it to master. There were a couple places that didn't expect anything except a `{ start, end }` object from `splitReactElement`.
> fix void elements in entityToHTML

- package.json
- src/convertToHTML.js
- test/spec/convertToHTML-test.js
Currently nested block types are specified as a constant:
```javascript
const NESTED_BLOCK_TYPES = [
'ordered-list-item',
'unordered-list-item'
];
```
This makes it difficult to render nested HTML for custom nested block types like the https://github.com/sugarshin/draft-js-checkable-list-plugin.
Given that this nesting information is already stored in the default block mapping file:
```javascript
export default {
...,
'unordered-list-item': {
element: <li />,
nest: <ul />
},
'ordered-list-item': {
element: <li />,
nest: <ol />
},
...
}
```
...we can get rid of the constant and allow providing custom nested block mapping like so:
```javascript
export const contentStateToHtml = convertToHTML({
blockToHTML: (block) => {
if (block.type === 'checkable-list-item') {
return {
element: <li …
```
> Custom nested block types

- src/encodeBlock.js
- test/spec/convertToHTML-test.js
same as #102 but on top of the most recent changes in`master`. thanks @tomkelsey for the original PR!
fixes #117
> use spread operator on resultText to get correct length in encodeBlock

- src/default/defaultBlockHTML.js
This has come up a couple times in #130 and #129 so I thought I'd might as well add it as a default value.
> add default blockToHTML value for atomic blocks

- src/convertToHTML.js
- test/spec/convertToHTML-test.js
This should hopefully prevent confusion like in #129 and #130 - the error will now explain what happened and what the block type was. It should also make it easier to debug further since there will be a check and specific `throw` line to add a breakpoint on instead of going through every `getBlockHTML` call
> add more useful error message when unable to convert a block

- src/convertFromHTML.js
- test/spec/convertFromHTML-test.js
This was preventing more than one inline style from surviving a `convertToHTML` -> `convertFromHTML` round trip.
> Stop resetting `inlineStyles` in `baseProcessInlineTag`

- .gitignore
- babel.config.js
- package.json
- yarn.lock
This is useful for bundlers like rollup which does not handle commonjs
out of the box.
Babel runtime allows to share helpers with other projects and save some bytes.
/cc @benbriggs @maxwellskala
> Add esm support

- src/convertToHTML.js
- src/default/defaultBlockHTML.js
- src/util/getNestedBlockTags.js
- test/spec/convertToHTML-test.js
draft-js strips standard ordered list styling using CSS and applies its own list indices using `:before` pseudo-elements. These indices match `type` attributes that can be applied to `<ol />` elements, but `convertToHTML` does not currently apply these `type` attributes when converting nested ordered lists.
This PR applies the `type` attribute based on list depth so that HTML-serialized Draft content more closely matches what the editor renders.
> Match ordered list styling from draft-js editor when converting to HTML

- src/blockEntities.js
- test/spec/blockEntities-test.js
`getElementHTML` can return both `undefined` and `null`, in which case `blockEntities` should replace that "html" with `originalText`. However, the existing check for this case was also replacing `''`, since it is falsy, meaing `'' || originalText` resolved to `originalText`.
Before this change, it was impossible to fully strip entity text when converting to HTML without including dummy tags with dummy children (e.g. `<span>{''}</span>`).
> Stop replacing empty string returns from entityToHTML with originalText

- src/default/defaultBlockHTML.js
- test/spec/convertToHTML-test.js
resolves https://github.com/HubSpot/draft-convert/issues/182
note this default behavior will wrap adjacent `code-block`s in separate `<pre>` tags and not try to do anything fancy in terms of combining blocks or the text in the block
> add default block HTML for code-block type
